### PR TITLE
Add links to the navbar

### LINKED ISSUE #5: Add links to the Navbar
From pod-3.1.2-portfolio created by [RashikaKarki](https://github.com/RashikaKarki): MLH-Fellowship/pod-3.1.2-portfolio#7  

Add links to the navbar to navigate to the relevant sections (eg. projects, experience) of the page.
Also, it would be great if we can have an option to choose whether we want to make the navbar sticky or not.

### PR DESCRIPTION
**Pull request by shreyaparadkar**
Closes #5

### CODE REVIEW

**Review by Rishit-dagli — CHANGES_REQUESTED** [review]
@shreyaparadkar 
Could you update it for #18 ?
Later we could probably update this for #19 too

**Comment by shreyaparadkar** [comment]
Committed the requested changes

**Review by Rishit-dagli — APPROVED** [review]
LGTM. What do you think @ayushmaang ?

**Review by harshgeek4coder — APPROVED** [review]
LGTM
👍

**Pull request merged**
