### PR TITLE
Add Resume

### LINKED ISSUE #11: Add Resume/CV
From pod-3.1.2-portfolio created by [RashikaKarki](https://github.com/RashikaKarki): MLH-Fellowship/pod-3.1.2-portfolio#1  

This portfolio acts very like your resume or CV but doesn't contain it. So maybe we can add a button for people to view/download your resume.

### PR DESCRIPTION
**Pull request by Rishit-dagli**
## :camera: Screenshots

screenshot

## :page_facing_up: Context

Add Resume link in navbar as discussed in #11 . Closes #11

## :pencil: Changes

Added a new item to the navbar

## :paperclip: Related PR

Based on top of #20 

## :no_entry_sign: Breaking

None

### CODE REVIEW

**Review by shreyaparadkar — APPROVED** [review]

**Review by harshgeek4coder — APPROVED** [review]
LGTM 
👍

**Comment by ayushmaang** [comment]
Looks good. although I'd suggest the resume button to look like one. Right now it looks like a link. Fix that and we can merge the branch.

**Comment by ayushmaang** [comment]
Looked like you already merged, so I'd suggest just pushing that later one.

**Comment by Rishit-dagli** [comment]
> Looked like you already merged, so I'd suggest just pushing that later one.

We (@harshgeek4coder @shreyaparadkar) thought the deadline was yesterday so we pushed changes hastily with just internal reviews to not miss the deadline.

> Looks good. although I'd suggest the resume button to look like one. Right now it looks like a link. Fix that and we can merge the branch.

Thanks so much for pointing that out.

**Pull request merged**
