### PR TITLE
Add Google Analytics tracking

### LINKED ISSUE #3: Add google analytics support
From pod-3.1.2-portfolio created by [RashikaKarki](https://github.com/RashikaKarki): MLH-Fellowship/pod-3.1.2-portfolio#9  

- Add config variable for google analytics tag and add same to the header.html
- Update the readme to direct how to configure this

### PR DESCRIPTION
**Pull request by Rishit-dagli**
Closes #3

### CODE REVIEW

**Review by harshgeek4coder — APPROVED** [review]
SGTM
👍

**Review by shreyaparadkar — APPROVED** [review]

**Comment by Rishit-dagli** [comment]
@ayushmaang Could you review this PR?

**Comment by ayushmaang** [comment]
Is the ga id stored locally? Otherwise everything else looks good.

**Comment by Rishit-dagli** [comment]
> Is the ga id stored locally? Otherwise everything else looks good.

@ayushmaang The Tracking ID is stored in `_config.yml`

https://github.com/Rishit-dagli/pod-3.1.2-portfolio/pull/17/files#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R14

**Pull request merged**
